protected/models/User.php
<?php

/**
 * This is the model class for table "user".
 *
 * The followings are the available columns in table 'user':
 * @property integer $id
 * @property integer $username
 * @property integer $password
 * @property integer $role_id
 * @property string $last_login
 * @property integer $status
 */
class User extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'user';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('username, password, role_id', 'required'),
			array('role_id, id_sekolah, status', 'numerical', 'integerOnly'=>true),
			array('password', 'length', 'max'=>255),
			array('last_login', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, username, password, role_id, last_login, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'Sekolah'=>array(self::BELONGS_TO,'Sekolah','id_sekolah'),
			'Role'=>array(self::BELONGS_TO,'Role','role_id')
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'username' => 'Username',
			'password' => 'Password',
			'role_id' => 'Role',
			'last_login' => 'Last Login',
			'status' => 'Status',
			'id_sekolah' => 'Sekolah'
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('username',$this->username);
		$criteria->compare('password',$this->password);
		$criteria->compare('role_id',$this->role_id);
		$criteria->compare('id_sekolah',$this->id_sekolah);
		$criteria->compare('last_login',$this->last_login,true);
		$criteria->compare('status',$this->status);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return User the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	
	public function getRelation($relation,$value)
	{
		if(!empty($this->$relation))
			return $this->$relation->$value;
		else
			return NULL;
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	* using two-column layout. See 'protected/views/layouts/column2.php'.
	*/
	public $layout='//layouts/admin/column2';

	/**
	* @return array action filters
	*/
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/
public function accessRules()
{
return array(
array('allow',  // allow all users to perform 'index' and 'view' actions
'actions'=>array('index','view'),
'users'=>array('*'),
),
array('allow', // allow authenticated user to perform 'create' and 'update' actions
'actions'=>array('create','update'),
'users'=>array('@'),
),
array('allow', // allow admin user to perform 'admin' and 'delete' actions
'actions'=>array('admin','delete'),
'users'=>array('admin'),
),
array('deny',  // deny all users
'users'=>array('*'),
),
);
}

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
public function actionView($id)
{
$this->render('view',array(
'model'=>$this->loadModel($id),
));
}

/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
public function actionCreate()
{
$model=new User;

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['User']))
{
$model->attributes=$_POST['User'];
if($model->save())
$this->redirect(array('view','id'=>$model->id));
}

$this->render('create',array(
'model'=>$model,
));
}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
public function actionUpdate($id)
{
$model=$this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['User']))
{
$model->attributes=$_POST['User'];
if($model->save())
$this->redirect(array('view','id'=>$model->id));
}

$this->render('update',array(
'model'=>$model,
));
}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
$dataProvider=new CActiveDataProvider('User');
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

/**
* Manages all models.
*/
public function actionAdmin()
{
$model=new User('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['User']))
$model->attributes=$_GET['User'];

$this->render('admin',array(
'model'=>$model,
));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=User::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/views/user/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'user-form',
	'enableAjaxValidation'=>false,
)); ?>

<p class="help-block">Fields with <span class="required">*</span> are required.</p>

<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldGroup($model,'username',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<?php echo $form->passwordFieldGroup($model,'password',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<?php echo $form->dropDownListGroup($model,'role_id',array('widgetOptions'=>array('data' => CHtml::listData(Role::model()->findAll(),'id','nama')))); ?>
	
	<?php echo $form->dropDownListGroup($model,'id_sekolah',array('widgetOptions'=>array('data' => CHtml::listData(Sekolah::model()->findAll(),'id','nama_sekolah')))); ?>

	<?php echo $form->dropDownListGroup($model,'status',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5'),'data'=>array('0'=>'Nonaktif','1'=>'Aktif')))); ?>

<div class="form-actions">
	<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			'context'=>'primary',
			'icon'=>'ok white',
			'label'=>$model->isNewRecord ? 'Tambah' : 'Simpan',
		)); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/user/_search.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldGroup($model,'id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'username',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'role_id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>
		
		<?php echo $form->textFieldGroup($model,'id_sekolah',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'last_login',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'status',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<div class="form-actions">
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType' => 'submit',
			'context'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/user/_view.php
<div class="view">

		<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('username')); ?>:</b>
	<?php echo CHtml::encode($data->username); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('password')); ?>:</b>
	<?php echo CHtml::encode($data->password); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('role_id')); ?>:</b>
	<?php echo CHtml::encode($data->role_id); ?>
	<br />
	
	<b><?php echo CHtml::encode($data->getAttributeLabel('id_sekolah')); ?>:</b>
	<?php echo CHtml::encode($data->role_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('last_login')); ?>:</b>
	<?php echo CHtml::encode($data->last_login); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('status')); ?>:</b>
	<?php echo CHtml::encode($data->status); ?>
	<br />


</div>

protected/views/user/admin.php
<?php
$this->breadcrumbs=array(
	'User'=>array('index'),
	'Kelola',
);

//$this->menu=array(
//array('label'=>'List Data Nasabah','url'=>array('index')),
//array('label'=>'Create Data Nasabah','url'=>array('create')),
//);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
$('.search-form').toggle();
return false;
});
$('.search-form form').submit(function(){
$.fn.yiiGridView.update('data-user-grid', {
data: $(this).serialize()
});
return false;
});
");
?>

<h1>DATA USER</h1>

<?php $this->widget('booster.widgets.TbButton',array(
        'buttonType'=>'link',
		'context'=>'primary',
		'url'=>array('user/create'),
		'label' => 'Tambah',
		'icon'=>'plus',
)); ?>


<?php $this->widget('booster.widgets.TbGridView',array(
		'id'=>'data-user-grid',
		'type'=>'striped bordered',
		'dataProvider'=>$model->search(),
		'filter'=>$model,
		'columns'=>array(
			'username',
			'password',
			array(
				'class'=>'CDataColumn',
				'name'=>'role_id',
				'header'=>'Role',
				'value'=>'$data->Role->nama'
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'id_sekolah',
				'header'=>'Sekolah',
				'value'=>'$data->getRelation("Sekolah","nama_sekolah")'
			),
			'last_login',
			array(
				'class'=>'CDataColumn',
				'name'=>'status',
				'header'=>'Status',
				'type'=>'raw',
				'value'=>'$data->status == 1 ? "Aktif" : "Nonaktif"',
				'filter'=>array('1'=>'Aktif','0'=>'Nonaktif')
			),
			array(
				'class'=>'booster.widgets.TbButtonColumn',
			),
		),
)); ?>

protected/views/user/create.php
<?php
$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Create',
);

/*$this->menu=array(
array('label'=>'List User','url'=>array('index')),
array('label'=>'Manage User','url'=>array('admin')),
);*/
?>

<h1>Tambah User</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/user/index.php
<?php
$this->breadcrumbs=array(
	'User',
);

/*$this->menu=array(
array('label'=>'Create User','url'=>array('create')),
array('label'=>'Manage User','url'=>array('admin')),
);*/
?>

<h1>User</h1>

<?php $this->widget('booster.widgets.TbListView',array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/views/user/update.php
<?php
$this->breadcrumbs=array(
	'User'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Perbaharui',
);

$this->menu=array(
	array('label'=>'Daftar User','url'=>array('index')),
	array('label'=>'Tambah User','url'=>array('create')),
	array('label'=>'Lihat User','url'=>array('view','id'=>$model->id)),
	array('label'=>'Kelola User','url'=>array('admin')),
);

?>

	<h1>Perbaharui User </h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/user/view.php
<?php
$this->breadcrumbs=array(
	'User'=>array('index'),
	$model->username,
);
/*
$this->menu=array(
	array('label'=>'Daftar User','url'=>array('index')),
	array('label'=>'Tambah User','url'=>array('create')),
	array('label'=>'Perbaharui User','url'=>array('update','id'=>$model->id)),
	array('label'=>'Hapus User','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Kelola User','url'=>array('admin')),
);
*/
?>

<h1>Lihat User</h1>

<?php $this->widget('booster.widgets.TbButton',array(
        'buttonType'=>'link',
		'context'=>'primary',
		'url'=>array('user/update','id'=>$model->id),
		'label' => 'Sunting User',
		'icon'=>'pencil',
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
        'buttonType'=>'link',
		'context'=>'primary',
		'url'=>array('user/admin'),
		'label' => 'Data User',
		'icon'=>'list',
)); ?>

<div>&nbsp;</div>

<?php $this->widget('booster.widgets.TbDetailView',array(
		'data'=>$model,
		'type'=>'striped bordered',
		'attributes'=>array(
			'username',
			'password',
			array(
				'label'=>'Role',
				'value'=>$model->Role->nama
			),
			array(
				'label'=>'Sekolah',
				'value'=>$model->getRelation("Sekolah","nama_sekolah"),
				'visible'=>$model->role_id == 1 ? "0" : "1"
			),
			array(
				'label'=>'Status',
				'value'=>$model->status == 1 ? "Aktif" : "Nonaktif"
			),
			'last_login',
		),
)); ?>