protected/models/Slide.php
<?php

/**
 * This is the model class for table "slide".
 *
 * The followings are the available columns in table 'slide':
 * @property integer $id
 * @property string $title
 * @property string $file
 */
class Slide extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Slide the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'slide';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title', 'required'),
			array('title, file', 'length', 'max'=>255),
			array('file','file','types'=>'jpg,JPG,png,PNG,gif,GIF','allowEmpty'=>true,'maxSize'=>1024*200,'tooLarge'=>'Gambar terlalu besar (maks: 200 KB). Silahkan resize terlebih dahulu'),
			array('time_created','safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, title, file', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'title' => 'Title',
			'file' => 'File',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('file',$this->file,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	public function getSlideList()
	{
		$models = Slide::model()->findAll(array('order'=>'id ASC'));
		
		$slides = array();
									
		foreach($models as $data)
		{
			$slide = array('src'=>Yii::app()->request->baseUrl.'/uploads/slide/'.$data->file,'caption'=>$data->title);
			array_push($slides,$slide);
		}
		
		return $slides;
	}
	
	public function getSlideImages()
	{
		$models = Slide::model()->findAll();
		
		$slides = array();
									
		foreach($models as $data)
		{
			$slide = $data->file;
			array_push($slides,$slide);
		}
		
		return $slides;
	}
	
	public function getSlideImage()
	{
		$models = Slide::model()->findAll();
		
		$slide = array();
									
		foreach($models as $data)
		{
			$slide[] = $data->file;
			
		}
		
		return $slide;
	}
	
	public function getSlideAlts()
	{
		$models = Slide::model()->findAll();
		
		$alts = array();
									
		foreach($models as $data)
		{
			$alt = $data->title;
			array_push($alts,$alt);
		}
		
		return $alts;
	}
	
	protected function beforeDelete()
	{
		$path = Yii::app()->basePath.'/../uploads/slide/';
		if($this->file!='' AND file_exists($path.$this->file))
			unlink($path.$this->file);
		
		return true;
	}
}

protected/controllers/SlideController.php
<?php

class SlideController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/admin/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('@'),
				//'expression'=>'Yii::app()->user->isAdmin()',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Slide;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Slide']))
		{
			$model->attributes=$_POST['Slide'];
			
			date_default_timezone_set("Asia/Jakarta");
			$model->time_created = date('y-m-d H:i:s');
			
			$file = CUploadedFile::getInstance($model,'file');
			
			if($file!==null)
				$model->file = str_replace(' ','-','_'.$file->name);
			
			if($model->save())
			{
				if($file!==null)
				{
					$path = Yii::app()->basePath.'/../uploads/slide/';
					$file->saveAs($path.$model->file);
				}
				
				Yii::app()->user->setFlash('success','Data berhasil ditambahkan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		$oldFile = $model->file;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Slide']))
		{
			$model->attributes=$_POST['Slide'];
			
			$file = CUploadedFile::getInstance($model,'file');
			
			if($file!==null)
				$model->file = str_replace(' ','-','_'.$file->name);
			else
				$model->file = $oldFile;
			
			if($model->save())
			{
				if($file!==null)
				{
					$path = Yii::app()->basePath.'/../uploads/slide/';
					$file->saveAs($path.$model->file);
				
					if(file_exists($path.$oldFile) AND $oldFile!='')
						unlink($path.$oldFile);
				}
				
				Yii::app()->user->setFlash('success','Data berhasil ditambahkan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Slide');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Slide('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Slide']))
			$model->attributes=$_GET['Slide'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Slide::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='slide-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/slide/_form.php
<script type="text/javascript">
function openKCFinder(field) {
    window.KCFinder = {
        callBack: function(url) {
            field.value = url;
            window.KCFinder = null;
        }
    };
    window.open('<?php print Yii::app()->request->baseUrl; ?>/vendors/kcfinder/browse.php?type=files&dir=files/public', 'kcfinder_textbox',
        'status=0, toolbar=0, location=0, menubar=0, directories=0, ' +
        'resizable=1, scrollbars=0, width=800, height=600'
    );
}
</script>

<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'slide-form',
	'enableAjaxValidation'=>false,
	'htmlOptions'=>array('enctype'=>'multipart/form-data')
)); ?>

	<p class="help-block">Kolom dengan <span class="required">*</span> harus diisi.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldGroup($model,'title',array('class'=>'span5','maxlength'=>255)); ?>
	
	<?php echo $form->labelEx($model,'file',array('label'=>'File (Ukuran 960px x 270px, Maksimal 200 KB)')); ?>
	<?php if($model->file!='') { ?>
	<?php print CHTml::image(Yii::app()->request->baseUrl.'/uploads/slide/'.$model->file); ?>
	<?php } ?>
	<?php echo $form->fileField($model,'file'); ?>
	<?php echo $form->error($model,'file'); ?>
	
	
	<div class="form-actions">
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			'context'=>'primary',
			'icon'=>'ok white',
			'label'=>'Simpan',
		)); ?>
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'link',
			'url'=>array('slide/admin'),
			'context'=>'primary',
			'icon'=>'list white',
			'label'=>'Kelola Slide',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/slide/_search.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'title',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'file',array('class'=>'span5','maxlength'=>255)); ?>

	<div class="form-actions">
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType' => 'submit',
			'context'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/slide/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('title')); ?>:</b>
	<?php echo CHtml::encode($data->title); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('file')); ?>:</b>
	<?php echo CHtml::encode($data->file); ?>
	<br />


</div>

protected/views/slide/admin.php
<?php
$this->breadcrumbs=array(
	'Slides'=>array('index'),
	'Manage',
);

$this->menu=array(
	//array('label'=>'List Slide','url'=>array('index')),
	//array('label'=>'Create Slide','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('slide-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Kelola Slide</h1>


<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'context'=>'primary',
		'icon'=>'plus white',
		'label'=>'Tambah Slide',
		'url'=>array('slide/create')
)); ?>


<?php $this->widget('booster.widgets.TbGridView',array(
	'id'=>'slide-grid',
	'dataProvider'=>$model->search(),
	'type'=>'striped bordered',
	'filter'=>$model,
	'columns'=>array(
		'title',
		array(
			'class'=>'CDataColumn',
			'header'=>'file',
			'type'=>'raw',
			'value'=>'CHtml::image(Yii::app()->request->baseUrl."/uploads/slide/".$data->file)'
		),
		array(
			'class'=>'booster.widgets.TbButtonColumn',
		),
	),
)); ?>

protected/views/slide/create.php
<?php
$this->breadcrumbs=array(
	'Slides'=>array('index'),
	'Create',
);

$this->menu=array(
	//array('label'=>'List Slide','url'=>array('index')),
	//array('label'=>'Manage Slide','url'=>array('admin')),
);
?>

<h1>Tambah Slide</h1>


<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/slide/index.php
<?php
$this->breadcrumbs=array(
	'Slides',
);

$this->menu=array(
	array('label'=>'Create Slide','url'=>array('create')),
	array('label'=>'Manage Slide','url'=>array('admin')),
);
?>

<h1>Slides</h1>

<?php $this->widget('booster.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/slide/update.php
<?php
$this->breadcrumbs=array(
	'Slides'=>array('index'),
	$model->title=>array('view','id'=>$model->id),
	'Update',
);
?>

<h1>Sunting Slide</h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/slide/view.php
<?php
$this->breadcrumbs=array(
	'Slides'=>array('index'),
	$model->title,
);

?>

<h1>Lihat Slide</h1>

<?php $this->widget('booster.widgets.TbButton',array('buttonType'=>'link','context'=>'primary','icon'=>'pencil white','label'=>'Sunting','url'=>array('slide/update','id'=>$model->id))); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array('buttonType'=>'link','context'=>'primary','icon'=>'plus white','label'=>'Tambah','url'=>array('slide/create'))); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array('buttonType'=>'link','context'=>'primary','icon'=>'list white','label'=>'Kelola','url'=>array('slide/admin'))); ?>






<div>&nbsp;</div>

<?php $this->widget('booster.widgets.TbDetailView',array(
	'data'=>$model,
	'type'=>'striped bordered',
	'attributes'=>array(
		'title',
		array(
			'label'=>'File',
			'context'=>'raw',
			'value'=>CHtml::image(Yii::app()->request->baseUrl.'/uploads/slide/'.$model->file)
		),
		'time_created',
	),
)); ?>