protected/models/Post.php
<?php

/**
 * This is the model class for table "post".
 *
 * The followings are the available columns in table 'post':
 * @property integer $id
 * @property integer $post_category_id
 * @property string $title
 * @property string $content
 */
class Post extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Post the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'post';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title', 'required'),
			array('post_category_id', 'numerical', 'integerOnly'=>true),
			array('title, thumbnail', 'length', 'max'=>255),
			array('thumbnail','file','allowEmpty'=>true,'types'=>'jpg,JPG,gif,GIF,png,PNG','maxSize'=>1024*150,'tooLarge'=>'File maksimal 150 KB'),
			array('content, created_time', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, post_category_id, title, content', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'post_category'=>array(self::BELONGS_TO,'PostCategory','post_category_id')
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'post_category_id' => 'Kategori',
			'title' => 'Judul',
			'content' => 'Konten',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('post_category_id',$this->post_category_id);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('content',$this->content,true);
		
		$criteria->order = 'created_time DESC';
		
		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	public function getCreatedTime()
	{
		return date('d-m-Y H:i:s',strtotime($this->created_time));
	}
	
	public function getThumbnail($htmlOptions=array())
	{
		return CHtml::image(Yii::app()->request->baseUrl.'/uploads/post/'.$this->thumbnail,'',$htmlOptions);
	}
	
	public function getDataDownload()
	{
		$model = Download::model()->findAllByAttributes(array('model'=>'Post','model_id'=>$this->id));
		
		if($model!==null)
			return $model;
		else
			return false;
	}
	
	public function getOtherPost()
	{
		$criteria = new CDbCriteria;
		$criteria->limit = 5;
		$criteria->order = 'created_time DESC';
		
		$model = Post::model()->findAll($criteria);
		
		if($model!==null)
			return $model;
		else
			return false;
	}
	
	public function getLatestPostByCategoryId($category_id=null,$limit=3)
	{
		if($category_id!=null)
		{
			$model = Post::model()->findAllByAttributes(array('category_id'=>$category_id),array('order'=>'created_time DESC','limit'=>$limit));
		} else {
			$model = Post::model()->findAll(array('order'=>'created_time DESC','limit'=>$limit));
		}
		
		if($model!==null)
			return $model;
		else
			return false;
		
	}
}

protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/admin/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('read'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index','create','update','view','chartByPostCategory'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('@'),
				//'expression'=>'Yii::app()->user->isAdmin()',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	
	public function actionRead($id)
	{
		$this->layout = '//layouts/column2';
		
		$this->render('read',array(
			'model'=>$this->loadModel($id),
		));
	}
	
	public function actionView($id)
	{
		
		
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Post;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			
			$thumbnail = CUploadedFile::getInstance($model,'thumbnail');
			
			if($thumbnail!==null)
				$model->thumbnail = str_replace(' ','-',time().'_'.$thumbnail->name);
			
			date_default_timezone_set('Asia/Jakarta');
			$model->created_time = date('Y-m-d H:i:s');
			
			if($model->save())
			{
				if($thumbnail!==null)
				{
					$path = Yii::app()->basePath.'/../uploads/post/';
					$thumbnail->saveAs($path.$model->thumbnail);
				}
				
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		
		
		$model=$this->loadModel($id);
		
		$old_thumbnail = $model->thumbnail;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			
			$thumbnail = CUploadedFile::getInstance($model,'thumbnail');
			
			if($thumbnail!==null)
				$model->thumbnail = str_replace(' ','-',time().'_'.$thumbnail->name);
			else
				$model->thumbnail = $old_thumbnail;
			
			if($model->save())
			{
				if($thumbnail!==null)
				{
					$path = Yii::app()->basePath.'/../uploads/post/';
					$thumbnail->saveAs($path.$model->thumbnail);
					
					if(file_exists($path.$old_thumbnail) AND $old_thumbnail!='')
						unlink($path.$old_thumbnail);
				}
				
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Post');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Post('search');
		
		$model->unsetAttributes();  // clear any default values
		
		if(isset($_GET['Post']))
			$model->attributes=$_GET['Post'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	
	public function actionChartByPostCategory()
	{
		Yii::app()->fusioncharts->setChartOptions(array(
			'caption'=>'Jumlah Post Berdasarkan Kategori', 
		));
		
		foreach(PostCategory::model()->findAll() as $data) 
		{
			Yii::app()->fusioncharts->addSet(array('label'=>$data->title, 'value'=>$data->countPost()));
		}
		
		Yii::app()->fusioncharts->getXMLData(true);
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Post::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='post-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/post/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'post-form',
	'enableAjaxValidation'=>false,
	'htmlOptions'=>array('enctype'=>'multipart/form-data')
)); ?>

	<p class="help-block">Kolom dengan <span class="required">*</span> harus diisi.</p>

	<?php echo $form->errorSummary($model); ?>

	
	<?php echo $form->textFieldGroup($model,'title',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->labelEx($model,'content'); ?>
	<?php $this->widget('ext.editMe.widgets.ExtEditMe', array(
			'model'=>$model,
			'attribute'=>'content',
			'filebrowserImageBrowseUrl'=>  Yii::app()->baseUrl.'/vendors/kcfinder/browse.php',
			'filebrowserImageBrowseLinkUrl'=>Yii::app()->baseUrl.'/vendors/kcfinder/browse.php?type=images',
			'filebrowserFlashBrowseUrl' => Yii::app()->baseUrl.'/vendors/kcfinder/browse.php?type=Flash',
	)); ?>
	<?php echo $form->error($model,'content'); ?> 
	
	<?php echo $form->dropDownListGroup($model,'post_category_id',CHtml::listData(PostCategory::model()->findAll(array('order'=>'title ASC')),'id','title')); ?>
	
	<?php print $form->labelEx($model,'thumbnail'); ?>
	<?php if(!empty($model->thumbnail)) print CHtml::image(Yii::app()->request->baseUrl.'/uploads/post/'.$model->thumbnail); ?>
	<?php echo $form->fileField($model,'thumbnail',array('class'=>'span5','maxlength'=>255)); ?>
	<?php print $form->error($model,'thumbnail'); ?>
	
	<div>&nbsp;</div>
	
	<div class="form-actions">
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			'context'=>'primary',
			'icon'=>'ok white',
			'label'=>'Simpan',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/post/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'post_category_id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'title',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textAreaRow($model,'content',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/post/_view - Copy.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('post_category_id')); ?>:</b>
	<?php echo CHtml::encode($data->post_category_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('title')); ?>:</b>
	<?php echo CHtml::encode($data->title); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('content')); ?>:</b>
	<?php echo CHtml::encode($data->content); ?>
	<br />


</div>

protected/views/post/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('post_category_id')); ?>:</b>
	<?php echo CHtml::encode($data->post_category_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('title')); ?>:</b>
	<?php echo CHtml::encode($data->title); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('content')); ?>:</b>
	<?php echo CHtml::encode($data->content); ?>
	<br />


</div>

protected/views/post/admin.php
<?php
$this->breadcrumbs=array(
	'Artikel'=>array('admin'),
	'Kelola',
);


Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('post-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Kelola Berita</h1>


<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'context'=>'primary',
		'icon'=>'plus white',
		'label'=>'Tambah Berita',
		'url'=>array('post/create')
)); ?>&nbsp;


<?php $this->widget('booster.widgets.TbGridView',array(
	'id'=>'post-grid',
	'dataProvider'=>$model->search(),
	'type'=>'striped bordered',
	'filter'=>$model,
	'columns'=>array(
		'title',
		array(
			'class'=>'CDataColumn',
			'name'=>'thumbnail',
			'type'=>'raw',
			'value'=>'$data->getThumbnail(array("width"=>"180px"))'
		),
		array(
			'class'=>'CDataColumn',
			'name'=>'post_category_id',
			'type'=>'raw',
			'value'=>'$data->post_category->title',
			'filter'=>CHtml::listData(PostCategory::model()->findAll(array('order'=>'title ASC')),'id','title')
		),
		array(
			'class'=>'CDataColumn',
			'name'=>'created_time',
			'type'=>'raw',
			'value'=>'$data->getCreatedTime()'
		),
		array(
			'class'=>'booster.widgets.TbButtonColumn',
		),
	),
)); ?>

protected/views/post/create.php
<?php
$this->breadcrumbs=array(
	'Artikel'=>array('admin'),
	'Tambah',
);

?>

<h1>Tambah Post</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/post/index - Copy.php
<?php
$this->breadcrumbs=array(
	'Posts',
);

$this->menu=array(
	array('label'=>'Create Post','url'=>array('create')),
	array('label'=>'Manage Post','url'=>array('admin')),
);
?>

<h1>Posts</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/post/index.php
<?php
$this->breadcrumbs=array(
	'Posts',
);

$this->menu=array(
	array('label'=>'Create Post','url'=>array('create')),
	array('label'=>'Manage Post','url'=>array('admin')),
);
?>

<div class="post-index">

<h1>Posts</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

</div>

protected/views/post/read.php
<?php
$this->breadcrumbs=array(
	'Posts'=>array('index'),
	$model->title,
);

$this->menu=array(
	array('label'=>'List Post','url'=>array('index')),
	array('label'=>'Create Post','url'=>array('create')),
	array('label'=>'Update Post','url'=>array('update','id'=>$model->id)),
	array('label'=>'Delete Post','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Post','url'=>array('admin')),
);
?>

<div class="margin20" id="post-read">

	<h3 class="list-bottom"><?php print strtoupper($model->post_category->title); ?></h3>

	<hr>

	<h3 class='post-read-title'><?php print $model->title; ?></h3>

	<div class='post-read-created-time'>
		<?php print Bantu::getWaktuDibuat($model->created_time); ?>
	</div>

	<?php if($model->thumbnail!='') print CHtml::image(Yii::app()->request->baseUrl.'/uploads/post/'.$model->thumbnail); ?>

	<div>&nbsp;</div>

	<?php print $model->content; ?>
	
	<div>&nbsp;</div>
	
	<h4>Berita Lainnya</h4>
	<ul>
	<?php foreach($model->getOtherPost() as $data) { ?>
	<li><?php print CHtml::link($data->title,array('post/read','id'=>$data->id)); ?></li>
	<?php } ?>
	</ul>
</div>

protected/views/post/update.php
<?php
$this->breadcrumbs=array(
	'Posts'=>array('index'),
	$model->title=>array('view','id'=>$model->id),
	'Update',
);

/*
$this->menu=array(
	array('label'=>'List Post','url'=>array('index')),
	array('label'=>'Create Post','url'=>array('create')),
	array('label'=>'View Post','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Post','url'=>array('admin')),
);
*/
?>

<h1>Sunting Post</h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/post/view.php
<?php
$this->breadcrumbs=array(
	'Posts'=>array('index'),
	$model->title,
);

/*
$this->menu=array(
	array('label'=>'List Post','url'=>array('index')),
	array('label'=>'Create Post','url'=>array('create')),
	array('label'=>'Update Post','url'=>array('update','id'=>$model->id)),
	array('label'=>'Delete Post','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Post','url'=>array('admin')),
);
*/
?>

<h1>Lihat Artikel</h1>

<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Sunting',
		'context'=>'primary',
		'icon'=>'pencil white',
		'url'=>array('/post/update','id'=>$model->id)
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Baca',
		'context'=>'primary',
		'icon'=>'search white',
		'url'=>array('/post/read','id'=>$model->id),
		'htmlOptions'=>array('target'=>'_blank')
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Tambah',
		'context'=>'primary',
		'icon'=>'plus white',
		'url'=>array('/post/create')
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Kelola',
		'context'=>'primary',
		'icon'=>'list white',
		'url'=>array('/post/admin')
)); ?>


<div>&nbsp;</div>

<?php $this->widget('booster.widgets.TbDetailView',array(
	'data'=>$model,
	'type'=>'striped bordered',
	'attributes'=>array(
		'title',
		array(
			'label'=>'Kategori',
			'type'=>'raw',
			'value'=>$model->post_category->title
		),
		array(
			'label'=>'Konten',
			'type'=>'raw',
			'value'=>$model->content
		),
		array(
			'label'=>'Thumbnail',
			'type'=>'raw',
			'value'=>$model->thumbnail == '' ? '' : CHtml::image(Yii::app()->request->baseUrl.'/uploads/post/'.$model->thumbnail)
		),
	),
)); ?>

<h2>File Unduhan</h2>
<?php $this->widget('bootstrap.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Tambah',
		'context'=>'primary',
		'icon'=>'plus white',
		'url'=>array('/download/create','model'=>'Post','model_id'=>$model->id)
)); ?>

<div>&nbsp;</div>

<table class='table'>
<tr>
	<th style="width:8%">No</th>
	<th>Judul</th>
	<th>Unduh</th>
	<th>Action</th>
</tr>
<?php $i=1; foreach($model->getDataDownload() as $data) { ?>
<tr>
	<td><?php print $i; ?></td>
	<td><?php print $data->title; ?></td>
	<td>
		<?php print CHtml::link('<i class="icon-download-alt"></i>',Yii::app()->request->baseUrl.'/uploads/download/'.$data->file,array('target'=>'_blank')); ?>
	</td>
	<td>
		<?php print CHtml::link('<i class="icon-pencil"></i>',array('download/update','id'=>$data->id)); ?>
		<?php print CHtml::link('<i class="icon-trash"></i>',array('download/hapus','id'=>$data->id)); ?>
	</td>
</tr>
<?php $i++; } ?>
</table>